"""empty message

Revision ID: ef5a17f4b363
Revises: 0a896d492301
Create Date: 2023-04-08 18:34:43.275612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5a17f4b363'
down_revision = '0a896d492301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('answer1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('answer2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('answer3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('correct_answer', sa.String(length=255), nullable=True))
        batch_op.drop_column('text')
        batch_op.drop_column('room')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('text', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('correct_answer')
        batch_op.drop_column('answer3')
        batch_op.drop_column('answer2')
        batch_op.drop_column('answer1')
        batch_op.drop_column('question')

    # ### end Alembic commands ###
